---
# Include the tasks depending on the zone type
- name: include_tasks master.yml
  include_tasks: master.yml
  loop: "{{ rgw_instances }}"
  loop_control:
    loop_var: outer_item
  when:
    - outer_item.rgw_zonemaster | default(rgw_zonemaster) | bool
    - not outer_item.rgw_zonesecondary | default(rgw_zonesecondary) | bool

- name: include_tasks secondary.yml
  include_tasks: secondary.yml
  loop: "{{ rgw_instances }}"
  loop_control:
    loop_var: outer_item
  when:
    - not outer_item.rgw_zonemaster | default(rgw_zonemaster) | bool
    - outer_item.rgw_zonesecondary | default(rgw_zonesecondary) | bool

- name: include_tasks start_radosgw.yml
  include_tasks: ../start_radosgw.yml
  with_items: "{{ rgw_instances }}"
  when:
    - not containerized_deployment | bool

- name: include_tasks start_docker_rgw.yml
  include_tasks: ../start_docker_rgw.yml
  with_items: "{{ rgw_instances }}"
  when:
    - containerized_deployment | bool

