---
- name: get num_pgs
  command: "{{ container_exec_cmd_update_osd | default('') }} ceph --cluster {{ cluster }} -s --format json"
  register: ceph_pgs
  delegate_to: "{{ groups[mon_group_name][0] }}"

- name: waiting for clean pgs...
  command: "{{ container_exec_cmd_update_osd | default('') }} ceph --cluster {{ cluster }} -s --format json"
  register: ceph_health_post
  until: >
    (((ceph_health_post.stdout | from_json).pgmap.pgs_by_state | length) > 0)
    and
    (((ceph_health_post.stdout | from_json).pgmap.pgs_by_state | selectattr('state_name', 'search', '^active\\+clean') | map(attribute='count') | list | sum) == (ceph_pgs.stdout | from_json).pgmap.num_pgs)
  delegate_to: "{{ groups[mon_group_name][0] }}"
  retries: "{{ health_osd_check_retries }}"
  delay: "{{ health_osd_check_delay }}"
  when: (ceph_pgs.stdout | from_json).pgmap.num_pgs != 0